INSERT INTO Alunos (idAluno, nome, sobrenome, curso) VALUES
(1, 'Joao', 'Silva', 'Engenharia Civil'),
(2, 'Maria', 'Souza', 'Medicina'),
(3, 'Carlos', 'Pereira', 'Direito'),
(4, 'Ana', 'Costa', 'Psicologia'),
(5, 'Pedro', 'Oliveira', 'Engenharia Mecanica'),
(6, 'Julia', 'Ferreira', 'Administracao'),
(7, 'Luis', 'Rodriguez', 'Arquitetura'),
(8, 'Sofia', 'Martinez', 'Ciencia da Computacao'),
(9, 'Miguel', 'Gonzalez', 'Biologia'),
(10, 'Laura', 'Lopez', 'Economia'),
(11, 'Gabriel', 'Garcia', 'Engenharia Eletrica'),
(12, 'Isabella', 'Hernandez', 'Contabilidade'),
(13, 'Matheus', 'Alves', 'Filosofia'),
(14, 'Rafaela', 'Nunes', 'Historia'),
(15, 'Lucas', 'Moreira', 'Educacao Fisica'),
(16, 'Beatriz', 'Lima', 'Nutricao'),
(17, 'Rafael', 'Araujo', 'Enfermagem'),
(18, 'Mariana', 'Ribeiro', 'Farmacia'),
(19, 'Fernando', 'Dias', 'Engenharia Civil'),
(20, 'Bruna', 'Carvalho', 'Engenharia de Software'),
(21, 'Daniel', 'Santos', 'Quimica'),
(22, 'Victoria', 'Campos', 'Fisica'),
(23, 'Andres', 'Ortiz', 'Matematica'),
(24, 'Camila', 'Ramirez', 'Geografia'),
(25, 'Jorge', 'Torres', 'Letras'),
(26, 'Fernanda', 'Barbosa', 'Pedagogia'),
(27, 'Ricardo', 'Gomes', 'Engenharia de Software'),
(28, 'Aline', 'Santana', 'Ciencia da Computacao'),
(29, 'Leonardo', 'Silveira', 'Engenharia Mecanica'),
(30, 'Patricia', 'Moraes', 'Engenharia Civil'),
(31, 'Jose', 'Miranda', 'Medicina'),
(32, 'Monica', 'Reis', 'Enfermagem'),
(33, 'Antonio', 'Cruz', 'Educacao Fisica'),
(34, 'Vanessa', 'Barros', 'Arquitetura'),
(35, 'Eduardo', 'Teixeira', 'Direito'),
(36, 'Renata', 'Mendes', 'Administracao'),
(37, 'Rodrigo', 'Duarte', 'Contabilidade'),
(38, 'Sandra', 'Mello', 'Economia'),
(39, 'Francisco', 'Farias', 'Psicologia'),
(40, 'Debora', 'Borges', 'Biologia'),
(41, 'Alice', 'Silva', 'Engenharia Civil'),
(42, 'Bruno', 'Oliveira', 'Engenharia Eletrica'),
(43, 'Carla', 'Santos', 'Engenharia Mecanica'),
(44, 'Diego', 'Ferreira', 'Medicina'),
(45, 'Elaine', 'Gomes', 'Direito'),
(46, 'Felipe', 'Costa', 'Administracao'),
(47, 'Gabriela', 'Martins', 'Contabilidade'),
(48, 'Henrique', 'Rocha', 'Economia'),
(49, 'Irene', 'Pereira', 'Psicologia'),
(50, 'Julio', 'Lima', 'Arquitetura'),
(51, 'Karina', 'Mendes', 'Ciencia da Computacao'),
(52, 'Leon', 'Rodriguez', 'Sistemas de Informacao'),
(53, 'Marta', 'Garcia', 'Biologia'),
(54, 'Nicolas', 'Lopez', 'Quimica'),
(55, 'Olivia', 'Hernandez', 'Fisica'),
(56, 'Paulo', 'Nunes', 'Matematica'),
(57, 'Renata', 'Araujo', 'Geografia'),
(58, 'Samuel', 'Ribeiro', 'Historia'),
(59, 'Tatiana', 'Alves', 'Letras'),
(60, 'Ulisses', 'Souza', 'Filosofia'),
(61, 'Veronica', 'Moreira', 'Pedagogia'),
(62, 'Walter', 'Dias', 'Educacao Fisica'),
(63, 'Ximena', 'Carvalho', 'Nutricao'),
(64, 'Yasmin', 'Campos', 'Enfermagem'),
(65, 'Zeca', 'Teixeira', 'Farmacia'),
(66, 'Arthur', 'Reis', 'Engenharia Civil'),
(67, 'Barbara', 'Miranda', 'Engenharia de Software'),
(68, 'Caio', 'Barbosa', 'Ciencia da Computacao'),
(69, 'Daniela', 'Silveira', 'Engenharia Mecanica'),
(70, 'Eduarda', 'Moraes', 'Engenharia Eletrica'),
(71, 'Fabio', 'Torres', 'Medicina'),
(72, 'Gustavo', 'Santana', 'Direito'),
(73, 'Helena', 'Cruz', 'Administracao'),
(74, 'Igor', 'Araujo', 'Contabilidade'),
(75, 'Janaína', 'Gomes', 'Economia'),
(76, 'Kelly', 'Ferreira', 'Psicologia'),
(77, 'Luis', 'Mendes', 'Arquitetura'),
(78, 'Mariana', 'Garcia', 'Ciencia da Computacao'),
(79, 'Nina', 'Rodriguez', 'Sistemas de Informacao'),
(80, 'Otavio', 'Lopez', 'Biologia'),
(81, 'Jean', 'Dupont', 'Engenharia Civil'),
(82, 'Isabella', 'Rossi', 'Engenharia Eletrica'),
(83, 'Hiroshi', 'Tanaka', 'Engenharia Mecanica'),
(84, 'Emma', 'Smith', 'Medicina'),
(85, 'Arjun', 'Patel', 'Direito'),
(86, 'Luc', 'Martin', 'Administracao'),
(87, 'Giulia', 'Bianchi', 'Contabilidade'),
(88, 'Yuki', 'Yamamoto', 'Economia'),
(89, 'James', 'Johnson', 'Psicologia'),
(90, 'Priya', 'Kumar', 'Arquitetura'),
(91, 'Marie', 'Lefevre', 'Ciencia da Computacao'),
(92, 'Alessandro', 'Russo', 'Sistemas de Informacao'),
(93, 'Sakura', 'Suzuki', 'Biologia'),
(94, 'Olivia', 'Williams', 'Quimica'),
(95, 'Aarav', 'Sharma', 'Fisica'),
(96, 'Chloe', 'Bernard', 'Matematica'),
(97, 'Marco', 'Conti', 'Geografia'),
(98, 'Rina', 'Kobayashi', 'Historia'),
(99, 'William', 'Brown', 'Letras'),
(100, 'Aisha', 'Mehta', 'Filosofia'),
(101, 'Noah', 'Miller', 'Pedagogia'),
(102, 'Elena', 'Ricci', 'Educacao Fisica'),
(103, 'Kenji', 'Watanabe', 'Nutricao'),
(104, 'Charlotte', 'Davis', 'Enfermagem'),
(105, 'Rahul', 'Singh', 'Farmacia'),
(106, 'Antoine', 'Dubois', 'Engenharia Civil'),
(107, 'Valentina', 'Ferrari', 'Engenharia de Software'),
(108, 'Takashi', 'Sato', 'Ciencia da Computacao'),
(109, 'Sophie', 'Meyer', 'Engenharia Mecanica'),
(110, 'Francesco', 'Gallo', 'Engenharia Eletrica'),
(111, 'Haruto', 'Yamada', 'Medicina'),
(112, 'David', 'Clark', 'Direito'),
(113, 'Kavya', 'Reddy', 'Administracao'),
(114, 'Matteo', 'Ricci', 'Contabilidade'),
(115, 'Akira', 'Kato', 'Economia'),
(116, 'Lucas', 'Taylor', 'Psicologia'),
(117, 'Nina', 'Verdi', 'Arquitetura'),
(118, 'Hana', 'Inoue', 'Ciencia da Computacao'),
(119, 'Benjamin', 'Harris', 'Sistemas de Informacao'),
(120, 'Lea', 'Nguyen', 'Biologia'),
(121, 'Sophia', 'Wang', 'Quimica'),
(122, 'Miguel', 'Hernandez', 'Fisica'),
(123, 'Adele', 'Morales', 'Matematica'),
(124, 'Emily', 'Martinez', 'Geografia'),
(125, 'Isabelle', 'Garcia', 'Historia'),
(126, 'Daniel', 'Rodriguez', 'Letras'),
(127, 'Lorenzo', 'Romano', 'Filosofia'),
(128, 'Keiko', 'Matsumoto', 'Pedagogia'),
(129, 'Michael', 'White', 'Educacao Fisica'),
(130, 'Elisa', 'Costa', 'Nutricao'),
(131, 'Juan', 'Ramirez', 'Enfermagem'),
(132, 'Sara', 'Sousa', 'Farmacia'),
(133, 'Tom', 'Baker', 'Engenharia Civil'),
(134, 'Anna', 'Gomes', 'Engenharia de Software'),
(135, 'Luis', 'Almeida', 'Ciencia da Computacao'),
(136, 'Alice', 'Dias', 'Engenharia Mecanica'),
(137, 'Jorge', 'Cunha', 'Engenharia Eletrica'),
(138, 'Pedro', 'Martins', 'Medicina'),
(139, 'Lucas', 'Fernandes', 'Direito'),
(140, 'Carlos', 'Moraes', 'Administracao'),
(141, 'Marie', 'Curie', 'Fisica'),
(142, 'Leonardo', 'da Vinci', 'Engenharia Civil'),
(143, 'Albert', 'Einstein', 'Matematica'),
(144, 'Nikola', 'Tesla', 'Engenharia Eletrica'),
(145, 'Isaac', 'Newton', 'Fisica'),
(146, 'Ada', 'Lovelace', 'Ciencia da Computacao'),
(147, 'Galileo', 'Galilei', 'Letras'),
(148, 'Charles', 'Darwin', 'Biologia'),
(149, 'Sigmund', 'Freud', 'Psicologia'),
(150, 'Antoine', 'Lavoisier', 'Quimica'),
(151, 'Carl', 'Sagan', 'Nutricao'),
(152, 'Rosalind', 'Franklin', 'Biologia'),
(153, 'Alan', 'Turing', 'Ciencia da Computacao'),
(154, 'Gregor', 'Mendel', 'Genetica'),
(155, 'Florence', 'Nightingale', 'Enfermagem'),
(156, 'Louis', 'Pasteur', 'Psicologia'),
(157, 'James', 'Watson', 'Biologia'),
(158, 'Francis', 'Crick', 'Biologia'),
(159, 'Marie', 'Lavoisier', 'Quimica'),
(160, 'Niels', 'Bohr', 'Fisica'),
(161, 'Max', 'Planck', 'Fisica'),
(162, 'Werner', 'Heisenberg', 'Fisica'),
(163, 'Erwin', 'Schrodinger', 'Fisica'),
(164, 'Richard', 'Feynman', 'Fisica'),
(165, 'Enrico', 'Fermi', 'Fisica'),
(166, 'Robert', 'Oppenheimer', 'Fisica'),
(167, 'Hans', 'Bethe', 'Fisica'),
(168, 'Ernest', 'Rutherford', 'Fisica'),
(169, 'Heinrich', 'Hertz', 'Fisica'),
(170, 'Wilhelm', 'Roentgen', 'Fisica'),
(171, 'Paul', 'Dirac', 'Fisica'),
(172, 'Subrahmanyan', 'Chandrasekhar', 'Pedagogia'),
(173, 'Stephen', 'Hawking', 'Fisica'),
(174, 'Lise', 'Meitner', 'Fisica'),
(175, 'Chien-Shiung', 'Wu', 'Fisica'),
(176, 'Dorothy', 'Hodgkin', 'Quimica'),
(177, 'Rosalyn', 'Yalow', 'Medicina'),
(178, 'Barbara', 'McClintock', 'Direito'),
(179, 'Gertrude', 'Elion', 'Medicina'),
(180, 'Rita', 'Levi-Montalcini', 'Letras'),
(181, 'Emmy', 'Noether', 'Matematica'),
(182, 'Katherine', 'Johnson', 'Matematica'),
(183, 'Mary', 'Jackson', 'Engenharia'),
(184, 'Dorothy', 'Vaughan', 'Matematica'),
(185, 'Mae', 'Jemison', 'Medicina'),
(186, 'Grace', 'Hopper', 'Ciencia da Computacao'),
(187, 'Margaret', 'Hamilton', 'Ciencia da Computacao'),
(188, 'Hedy', 'Lamarr', 'Engenharia de Software'),
(189, 'Sally', 'Ride', 'Fisica'),
(190, 'Valentina', 'Tereshkova', 'Engenharia de Software'),
(191, 'Ellen', 'Ochoa', 'Engenharia'),
(192, 'Jane', 'Goodall', 'Biologia'),
(193, 'Rachel', 'Carson', 'Biologia'),
(194, 'Marie', 'Tharp', 'Fisica'),
(195, 'Inge', 'Lehmann', 'Fisica'),
(196, 'Maria', 'Goeppert-Mayer', 'Fisica'),
(197, 'Carolyn', 'Porco', 'Psicologia'),
(198, 'Vera', 'Rubin', 'Arquitetura'),
(199, 'Annie', 'Jump Cannon', 'Contabilidade'),
(200, 'Cecilia', 'Payne-Gaposchkin', 'Economia');

SET SQL_SAFE_UPDATES = 0;
UPDATE Alunos SET email = CONCAT(nome, '.', sobrenome, '@dominio.com');

DELIMITER $
CREATE TRIGGER gerarEmailAluno
BEFORE INSERT ON Alunos
FOR EACH ROW
BEGIN
	SET NEW.email = CONCAT(NEW.nome, '.', NEW.sobrenome, '@dominio.com');
END;
$
DELIMITER ;    
-- testando a trigger criada
INSERT INTO Alunos (nome, sobrenome) VALUES ('Guilherme', 'Souza');

DELIMITER $
CREATE PROCEDURE matricularAluno(
IN idAluno INT,
IN nome VARCHAR(20),
IN sobrenome VARCHAR(20),
IN curso VARCHAR(30),
IN area VARCHAR(30)
)
BEGIN
	DECLARE v_idCurso INT;	
        
	INSERT INTO Alunos (idAluno, nome, sobrenome, email, curso)
	VALUES (idAluno, nome, sobrenome, email, curso);
	SELECT 'Matrícula feita com sucesso!' AS mensagem;
END;
$
DELIMITER ;     
-- testando a procedure criada
CALL matricularAluno(201,'Fagner', 'Mendes', 'Pedagogia', 'Ciências Humanas');
CALL matricularAluno(202,'Juliana', 'Dutra', 'Psicologia', 'Ciências Humanas');
